backend:
  name: github
  repo: joshuaewatkins/okolona-church-site
  branch: main
  base_url: https://okolona-auth.joshuaewatkins.workers.dev
  auth_endpoint: /auth

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "src/content/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
